# Imagen base de PHP con FPM
FROM php:8.2-fpm

# Crear el usuario y grupo nginx
RUN addgroup --system nginx && adduser --system --ingroup nginx nginx

# Instalar Nginx, supervisor y dependencias necesarias
RUN apt-get update && apt-get install -y \
    nginx \
    supervisor \
    git \
    curl \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev \
    libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo_mysql mbstring exif pcntl bcmath gd pdo pdo_pgsql

# Limpiar la cache de APT
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiar configuración de Nginx y supervisor
COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY .docker/supervisor/supervisord.conf /etc/supervisor/supervisord.conf

# Establecer el directorio de trabajo
WORKDIR /var/www

# Copiar los archivos del proyecto
COPY . .

# Copiar el archivo .env desde .env.example
RUN cp .env.example .env

# Instalar Composer y dependencias
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN composer install --no-dev --optimize-autoloader

# Generar la clave de la aplicación
RUN php artisan key:generate

# Establecer permisos para los archivos
RUN chown -R nginx:nginx /var/www

# Exponer los puertos necesarios
EXPOSE 80 9000

# Comando por defecto para iniciar Nginx y PHP-FPM con supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
