FROM php:8.2-fpm

ENV USER=www
ENV GROUP=www

# Instalar dependencias del sistema y PHP
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libpq-dev \
    libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo_mysql mbstring exif pcntl bcmath gd pdo pdo_pgsql

# Limpiar cache de APT
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiar Composer desde la imagen oficial
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Crear usuario y grupo
RUN groupadd -g 1000 ${GROUP} && useradd -u 1000 -ms /bin/bash -g ${GROUP} ${USER}

# Establecer el directorio de trabajo
WORKDIR /var/www

# Asignar permisos
RUN chown -R ${USER}:${GROUP} /var/www

# Cambiar a usuario no root
USER ${USER}

# Copiar archivos del proyecto
COPY --chown=${USER}:${GROUP} . .

# Instalar dependencias de Composer
RUN composer install --no-dev --optimize-autoloader

# Exponer puerto para PHP-FPM
EXPOSE 9000

# Comando por defecto
CMD ["php-fpm"]
